# Changes here will be overwritten by Copier
_commit: '1.0'
_src_path: copier-pytup-2022
author_fullname: Dislate
copyright_date: 2022
project_description: null
project_name: Workshop
python_package_name: workshop

